image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        name: Build and test
        script:
          - npm install
          - npm run test
  branches:
    master:
      - step:
          name: production
          script:
          - npm install serverless -g
          - serverless config credentials --stage production --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
          - sls deploy --stage production

    uat:
      - step:
          name: uat
          script:
          - npm install serverless -g
          - serverless config credentials --stage uat --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
          - sls deploy --stage uat


    dev:
      - step:
          name: dev
          script:
          - npm install serverless -g
          - serverless config credentials --stage dev --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
          - sls deploy --stage dev